jobs:
  main:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Get Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./run/action

name: Check

on:
  schedule:
    - cron: "20 */3 * * *"
